[package]
name = "bevy_stat_query"
version = "0.0.3"
edition = "2021"

authors = ["Mincong Lu <mintlux667@gmail.com>"]
license = "MIT OR Apache-2.0"

readme = "README.md"
repository = "https://github.com/mintlu8/bevy_stat_query"
description = """
An over-engineered RPG stat query system for the bevy engine.
"""
keywords = ["bevy", "stat", "serialize"]

[features]
default = ["futures"]

[lib]
doctest = false

[dependencies]
bevy_ecs = { version = "^0.13" }
bevy_hierarchy = { version = "^0.13" }
bevy_app = { version = "^0.13" }
bevy_reflect = { version = "^0.13" }
bevy_utils = { version = "^0.13" }
downcast-rs = "^1.2"
dyn-hash = "^0.2"
dyn-clone = "1.0.17"
serde = { version = "^1", features = ["derive"] }
erased-serde = "0.4.3"
ref-cast = "^1"
thiserror = "^1"
num-integer = { version = "^0.1", default-features = false }
num-rational = { version = "^0.4.1", default-features = false, features = ["serde"] }
num-traits = { version = "0.2.18", default-features = false }
bevy_serde_project = { version = "^0.1.2" }
parking_lot = "0.12.1"
futures = { version = "0.3.30", default-features = false, features = ["std"], optional = true }

[dev-dependencies]
bevy = "0.13.1"
bevy_defer = { version = "0.8.2", default-features = false }
bitflags = "2.4.2"
postcard = { version = "1.0.8", features = ["alloc"], default-features = false }
serde_json = "1.0.114"
